# Site settings
title: Imchaewon
email: imchaewon26@gmail.com
description: This page is Im Chaewon Homepage.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imchaewon.github.io" # the base hostname & protocol for your site

# Identity
your-name: Im Chaewon
your-title: Backend Engineer

# Social settings
500px_url:
facebook_url: https://facebook.com/profile.php?id=100005942894033
github_url: https://github.com/imchaewon
gitlab_url: 
googleplus_url:
instagram_url: https://www.instagram.com/chaewwwon/
linkedin_url: https://www.linkedin.com/in/chaewon-im-576111209
pinterest_url:
slack_url:
twitter_url: 
pf_url: https://imchaewon.github.io/portfolio/
blog_url: https://yeoumul.tistory.com/  

# Build settings
markdown: kramdown
